config/routes.rb
Rails.application.routes.draw do
  get 'subscription/new'
  get 'subscription/create'
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  resources :subscriptions, only: %i[index show] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[destroy]
  resources :reviews
  resources :courses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :subscription

  validates :total_price, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :subscription

  validates :date, :available_places, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user

  validates :content, presence: true,  length: { maximum: 200,
    too_long: "%{count} lettres est le maximum autorisé." }
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :courses
  has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :phone_number, :level, :health_record])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :age, :phone_number, :level, :health_record])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :total_price)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, only: %i[destroy]


  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def course_params
    params.require(:course).permit(:date, :available_places)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @reviews = Review.all
  end

  def dashboard
    @bookings = current_user.bookings
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path, status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :date)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @subscriptions = Subscription.all
  end

  def show
    @subscription = Subscription.find(params[:id])
    @courses = Course.all
    @booking = Booking.new
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.user = current_user
    if @subscription.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def subscription_params
    params.require(:subscription).permit(:type, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
 <%# <%= simple_form_for @course do |f| %>
 <%# <%= f.input :subscription_type %> %>
 <%# <%= f.input :date %> %>
 <%# <%= f.input :trial_course, :as => :radio %> %>
 <%# <%= f.total_price %> %>
 <%# <%= f.button "Confirmer et payer" %> %>
 <%# <% end %> %> %>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/new.html.erb
<div class="container my-3">
  <h1 class="text-center">new booking</h1>

  <%= render "form", bookings: @bookings, courses: @courses%>

</div>

app/views/courses/create.html.erb
<h1>Courses#create</h1>
<p>Find me in app/views/courses/create.html.erb</p>

app/views/courses/destroy.html.erb
<h1>Courses#destroy</h1>
<p>Find me in app/views/courses/destroy.html.erb</p>

app/views/courses/new.html.erb
<div class="container my-3">
  <h1 class="text-center">Espace administrateur </h1>
  <h2>Créer des nouveaux cours</h2>
    <div>
      <%= simple_form_for @course do |f| %>
      <%= f.input :date, order: [:day, :month, :year], type: "datetime-local", fr:  %>
      <%= f.input :available_places, collection: 1..6,
                  label: "Nombre de places disponibles" %>
      <%= f.submit "Rendre visible ce cours", class: "button2" %>
      <% end %>
    </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiliPilates</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body class="background-color body">
    <%= render "shared/navbar"%>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/_carroussel.html.erb
<% if @reviews.empty? %>
  <p class="mute"><em>Soyez la première personne à laisser un avis !</em></p>
<% else %>
<div id="carouselExampleControls" class="carousel slide carousel-dark slider" data-ride="carousel" >
  <div class="carousel-inner my-3 ">
    <% @reviews.each do |review| %>
      <div class="carousel-item active " >
        <div class=" card-review">
          <div class="d-flex justify-content-between">
            <h3><%= review.user.last_name.capitalize %> <%= review.user.first_name %></h3>
            <h3><%= review.date %></h3>
          </div>
          <p class="text-truncate" ><%= review.content %></p>
          <p class= "text-center"><%= link_to "Voir plus", reviews_path %></p>
        </div>
      </div>
    <% end %>
  </div>

  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
</div>

<% end %>

app/views/pages/dashboard.html.erb
<div class="container my-3">
  <h1 class="text-center">Mon espace</h1>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= asset_path 'Lisa-home.jpg' %>');">
  <div class="container text-center ">
    <div class="banner-text">
      <h1>Prendre soin de soi grâce au Pilates </h1>
      <h2> Renforcer son corps & trouver son équilibre </h2>
    </div>
    <div class="banner-space">
      <%= link_to "Réserver un cours", subscriptions_path, class:"button2" %>
      <p>*La première séance est gratuite !</p>
    </div>
  </div>
</div>

<div class="container">
  <div class=" col-6 my-3 text-end card-space">
    <h1>Qui suis-je ? </h1>
    <h3 >Rémy et Mélanie ont trente ans et vivent dans le même quartier à Paris. Elle multiplie les rendez-vous ratés sur les réseaux sociaux pendant qu'il peine à faire une rencontre. Tous les deux victimes de cette solitude des grandes villes, à l’époque hyper connectée où l’on pense pourtant que se rencontrer devrait être plus simple… Deux individus, deux parcours. Sans le savoir, ils empruntent deux routes qui les mèneront dans une même direction… celle d’une histoire amour ?</h3>
  </div>
  <div class="d-flex justify-content-end">
    <div class=" col-6 my-3 text-start card-space">
      <h1>Qu'est-ce que je propose ? </h1>
      <h3 >Rémy et Mélanie ont trente ans et vivent dans le même quartier à Paris. Elle multiplie les rendez-vous ratés sur les réseaux sociaux pendant qu'il peine à faire une rencontre. Tous les deux victimes de cette solitude des grandes villes, à l’époque hyper connectée où l’on pense pourtant que se rencontrer devrait être plus simple… Deux individus, deux parcours. Sans le savoir, ils empruntent deux routes qui les mèneront dans une même direction… celle d’une histoire amour ?</h3>
    </div >
  </div>

  <div class="my-3 text-center card-space">
    <h1>En savoir plus sur l'histoire du Pilates </h1>
    <h3>Rémy et Mélanie ont trente ans et vivent dans le même quartier à Paris. Elle multiplie les rendez-vous ratés sur les réseaux sociaux pendant qu'il peine à faire une rencontre. Tous les deux victimes de cette solitude des grandes villes, à l’époque hyper connectée où l’on pense pourtant que se rencontrer devrait être plus simple… Deux individus, deux parcours. Sans le savoir, ils empruntent deux routes qui les mèneront dans une même direction… celle d’une histoire amour ?</h3>
  </div>
  <div class="my-5 text-center">
    <%= link_to "Réserver un cours", subscriptions_path, class:"button2" %>
    <p class=" my-3">*La première séance est gratuite !</p>
  </div>

</div>
  <div class=" card-space row" >
    <div class="col-6 banner-bottom" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= asset_path 'Lisa-home-bottom.jpg' %>');" >
    </div>
    <div class="col-6">
      <h2 class="text-center my-3 ">Vos avis (<%= @reviews.count %>)</h2>
      <div>
        <%= render "pages/carroussel", home: @home %>
      </div>
      <div class="mt-3 mb-5 justify-content-center d-flex ">
        <span><%= link_to "Tous les avis", reviews_path %> </span>  |  <span><%= link_to "Laisser un avis", new_review_path(@review) %></span>
      </div>
    </div>
  </div>
</div>
  <div class="text-end my-3 container ">
   <%= link_to "", root_path, class: "fa-solid fa-angles-up text-decoration-none" %>
  </div>

<div class="row">
  <div class="footer">
    <div class="my-1 col-8">
    </div>
    <div class="footer-links">
      <h3 class="my-1">Retrouvez moi sur Instagram:</h3>
      <a href="https://www.instagram.com/lisa.physiopilates/?hl=fr" class="fab fa-instagram"></a>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="container">
  <h1 class="text-center my-3 ">Vos avis (<%= @reviews.count %>)</h1>
    <div class="row justify-content-around" >
     <% @reviews.each do |review| %>
        <div class="col-3 card-review m-3 ">
         <div class="d-flex justify-content-between">
            <h3><%= review.user.last_name.capitalize %> <%= review.user.first_name %></h3>
            <h3><%= review.date %></h3>
          </div>
          <p><%= review.content %></p>
        </div>
      <% end %>
    </div>

  <div class="text-center my-5">
    <%= link_to "Laisser un avis", new_review_path(@review), class: "button2" %>
  </div>
   <div class="text-center my-3 container ">
   <%= link_to "", reviews_path, class: "fa-solid fa-angles-up text-decoration-none" %>
  </div>


</div>


<div class="row">
  <div class="footer">
    <div class="my-1 col-8">
    </div>
    <div class="footer-links">
      <h3 class="my-1">Retrouvez moi sur Instagram:</h3>
      <a href="https://www.instagram.com/lisa.physiopilates/?hl=fr" class="fab fa-instagram"></a>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container my-3"><h1>Votre avis</h1>
  <%= simple_form_for @review do |f| %>
  <%= f.input  :date,
              order: [:day, :month, :year],
               hint: "*La date de votre commentaire sera automatiquement celle d'aujourd'hui" %>
  <%= f.input :content,
              hint: "200 caractères maximum.",
              label: "Laissez un commentaire ici : " %>
    <%= f.button :submit, "Valider", class: "button2" %>
  <% end %>
    <div class="my-3">
      <%= link_to "Retour à la page d'accueil", root_path %>
    </div>
</div>

app/views/shared/_flashes.html.erb
<%# <% if notice %>
  <%# <div class="alert alert-info alert-dismissible fade show m-1" role="alert"> %>
    <%# <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> %>
    <%# <h3>Vous êtes connecté.e !</h3> %>
  <%# </div> %>
<%# <% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <h3>Vous devez vous connecter ou créer un compte pour pouvoir continuer.</h3>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" >
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://w7.pngwing.com/pngs/703/626/png-transparent-yoga-pilates-mats-shoulder-silhouette-yoga-physical-fitness-hand-sports.png"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto ">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Présentation", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Réserver un cours", subscriptions_path , class: "nav-link" %>
          </li>
          <li class="nav-item dropdown ">
          <a href="#" class="fa-solid fa-bars nav-link my-1" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon espace", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Me déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/subscriptions/_form.html.erb
 <% if @subscription.courses.any?%>
 <div class="row  my-3">
    <% @courses.sort_by(&:date).each do |course| %>
      <div class="card-course">
        <h3> <%= course.date.strftime("%A %d %B") %> à <%= course.date.time.strftime("%kh%M") %></h3>
          <p class="my-1"> <%= course.available_places%> places disponibles !</p>
          <div class="d-flex justify-content-center align-items-center">
          <p class="m-2" >Choisir :</p>
         <%= simple_form_for [@subscription, @booking] do |f| %>
            <%= f.submit '',
            type: :checkbox %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="my-5 text-center">
      <%= link_to "Confirmer",  new_subscription_booking_path(subscription), class: "button2" %>
    </div>
  </div>


      <%= %>
  <% else %>
    <p>nop</p>
  <% end %>

app/views/subscriptions/create.html.erb
<h1>Subscription#create</h1>
<p>Find me in app/views/subscription/create.html.erb</p>

app/views/subscriptions/index.html.erb
<div class="container my-3">
  <h1 class="text-center">Réserver un cours</h1>
  <h3 class="my-3 text-center">Les cours sont donnés en présentiel à l’adresse suivante : <strong>48 CHEMIN DE ROUFFIAC 31200 ROUFFIAC </strong>et durent <strong>50 minutes</strong>. </h3>
  <div>
    <h2>ETAPE 1 : SELECTIONNER VOTRE TYPE D’ABONNEMENT</h2>
    <p>Si vous souhaitez essayer le pilates, <strong>la première séance est gratuite.</strong></p>
    <div class="align-self-center">
      <% @subscriptions.each do |subscription|  %>
      <div class=" my-4 col-6 card-abo">
        <h3> <strong><%= subscription.sub_type %></strong> - <%= subscription.price %>€</h3>
        <p><%= link_to "Choisir", subscription_path(subscription)%></p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/subscriptions/new.html.erb
<h1>Subscription#new</h1>
<p>Find me in app/views/subscription/new.html.erb</p>

app/views/subscriptions/show.html.erb
<div class="container my-3">
  <h1 class="text-center">Réserver un cours</h1>
  <h3 class="my-3 text-center">Les cours sont donnés en présentiel à l’adresse suivante : <strong>48 CHEMIN DE ROUFFIAC 31200 ROUFFIAC </strong>et durent <strong>50 minutes</strong>. </h3>
  <div>
    <h2>ETAPE 1 : SELECTIONNER VOTRE TYPE D’ABONNEMENT</h2>
      <h3 class="my-2" >Vous avez choisi cette option-ci :</strong></h3>
      <div class="align-self-center">
        <div class=" my-4 col-6 card-abo">
          <h3> <strong><%= @subscription.sub_type %></strong> - <%= @subscription.price %>€</h3>
        </div>
      </div>
      <h3 class="my-3 text-decoration-none"><%=link_to "Modifier mon choix", subscriptions_path%>  </h3>
  </div>
  <h2 class="my-4">ETAPE 2 : SELECTIONNER UNE (OU plusieurs) date(s)</h2>
    <%= render "form", subscription: @subscription  %>
</div>